version: "3.8"

services:
  game-app:
    build: .
    container_name: game-app_container
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "2000-2020:2000-2020/udp"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - COOKIE_SECRET_KEY=${COOKIE_SECRET_KEY}
      - COOKIE_REFRESH_SECRET=${COOKIE_REFRESH_SECRET}
      - ANNOUNCED_IP=${ANNOUNCED_IP}
      - QUEUE_URL=amqp://aditya:Aditya%4001@rabbitmq:5672

    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_container
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: aditya
      RABBITMQ_DEFAULT_PASS: Aditya@01
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
